# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Create a downloads directory
RUN mkdir -p /app/downloads

# Copy requirements.txt into the container
COPY ../requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the modules directory and the example script into the container
COPY ../modules /app/modules
COPY validation/example_1_service_account.py ./

# Run the Python script when the container launches
CMD ["python", "example_1_service_account.py"]
